# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
- uses: actions-rs/toolchain@v1
  with:
    toolchain: nightly
    override: true
    components: rustfmt, clippy
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
