# This is a basic workflow to help you get started with Actions

name: Filter Testing

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - develop
  # Triggers the workflow on push or pull request events but only for the master branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## We don't need to even download files, we only need the docker container.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    container: 
#      image: securesystemslab/lind
#      options: --privileged --ipc=host --cap-add=SYS_PTRACE
    
    #  options: --privileged --ipc=host --cap-add=SYS_PTRACE

    steps:
      # Runs a set of commands using the runners shell
    
      - name: Echo out branch and pr username values
        run: | 
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          echo github.user.login: ${{ github.event.pull_request.user.login }}
          
      - name: Do stuff
        run: |
          echo "Kinda limited POWER"
          if: (${{ github.event.pull_request.user.login }} == 'kapkic')
          echo "UNLIMITED POWER"
                    
